//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarfSG.GetProxyListClient.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GarfSG.GetProxyListClient.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;_links&quot;: {
        ///        &quot;_self&quot;: &quot;\/proxy&quot;,
        ///        &quot;_parent&quot;: &quot;\/&quot;
        ///    },
        ///    &quot;ip&quot;: &quot;148.103.49.247&quot;,
        ///    &quot;port&quot;: 21776,
        ///    &quot;protocol&quot;: &quot;http&quot;,
        ///    &quot;anonymity&quot;: &quot;high anonymity&quot;,
        ///    &quot;lastTested&quot;: &quot;2018-08-20 10:54:09&quot;,
        ///    &quot;allowsRefererHeader&quot;: true,
        ///    &quot;allowsUserAgentHeader&quot;: true,
        ///    &quot;allowsCustomHeaders&quot;: true,
        ///    &quot;allowsCookies&quot;: true,
        ///    &quot;allowsPost&quot;: true,
        ///    &quot;allowsHttps&quot;: true,
        ///    &quot;country&quot;: &quot;DO&quot;,
        ///    &quot;connectTime&quot;: &quot;0.180&quot;,
        ///    &quot;downloadSpeed&quot;: &quot;17.000&quot;,
        ///    &quot;seconds [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidGetProxyResponse {
            get {
                return ResourceManager.GetString("ValidGetProxyResponse", resourceCulture);
            }
        }
    }
}
